decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn sonar:sonar -Dsonar.organization=vatavuk-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=fab2491238f62fae758d576256b78b365c7334d1
    mvn clean deploy -Pqulice -Psonatype -Pvgv-xls --settings /home/r/settings.xml
