decrypt:
  settings.xml: "vgv-xls/settings.xml.asc"
  pubring.gpg: "vgv-xls/pubring.gpg.asc"
  secring.gpg: "vgv-xls/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pjcabi --settings /home/r/settings.xml
